language: node_js

node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

script: grunt test --verbose

after_script:
  - codeclimate-test-reporter < report/lcov.info
